现在能够清除assignee和deadline
zkuang/laixi-vue pull request #3
Opened 2017-07-11 15:48 UTC by JefferyLiang

修改了TaskAssignmentEditor.vue和TaskItem.vue的代码。

用户可以清除assignee或者deadline了。

2017-07-13 03:36 UTC, zkuang commented on src/components/DiscussionItems.vue
> +      if (routeName.includes('Draft')) this.$store.dispatch('getDraftPosts', this.$route.params.did)
是不是应该先做api请求，然后改变show post number？
然后routeName为什么不直接用相等比较？为什么用includes？

2017-07-13 03:36 UTC, zkuang commented on src/components/DiscussionItems.vue
> +    showAll () {
showAll改成noMore会不会更加容易理解？

2017-07-13 03:36 UTC, zkuang commented on src/components/TaskAssignmentEditor.vue
> +  <div class="field" style="position: relative;">
为什么不放在field class的css里面？

2017-07-13 03:36 UTC, zkuang commented on src/components/TaskAssignmentEditor.vue
> +    <div class="ui calendar" :id="datePickerId" style="position: relative;">
增加一个class给这里的修改？

2017-07-13 12:39 UTC, JefferyLiang commented on src/components/DiscussionItems.vue
> +      if (routeName.includes('Draft')) this.$store.dispatch('getDraftPosts', this.$route.params.did)
在api那边，我修改了getPost的参数，多了一个number。是根据当前在vuex里的showPostNumber的。

所以我们需要先set了showPostNumber再去调用api。

2017-07-13 12:39 UTC, JefferyLiang commented on src/components/DiscussionItems.vue
> +    showAll () {
这个可以去我去修改一下。

2017-07-13 12:39 UTC, JefferyLiang commented on src/components/TaskAssignmentEditor.vue
> +  <div class="field" style="position: relative;">
不能放在field里面。因为我们组件的style不是scoped的，怕会影响到其他地方。

如果不直接写在style可以多添加一个css类。

2017-07-13 12:42 UTC, zkuang commented on src/components/DiscussionItems.vue
> +      if (routeName.includes('Draft')) this.$store.dispatch('getDraftPosts', this.$route.params.did)
修改内部状态之后，如果api请求出错就需要roll back，但没看到相关的处理代码

2017-07-14 01:39 UTC, zkuang requested changes

2017-07-14 01:39 UTC, zkuang commented on src/store/index.js
>        return Posts.getPostsByDraftId(draftId, state.showPostNumber).then(res => {
state.showPostNumber应该是getCount吧？

2017-07-14 02:36 UTC, zkuang requested changes

2017-07-14 02:36 UTC, zkuang commented on src/components/DiscussionItems.vue
> +    showAll () {
noMore在post增加到超过250条之后没有让加载按钮显示出来

2017-07-14 07:59 UTC, JefferyLiang commented
之前需要刷新页面的才会出现提示更多信息的问题是因为在请求posts时候，每次调用又为vuex中的showPostNumber自增了250，而不是我们点击显示更多时候才去增加showPostNumber。

导致了showPost永远大于totalPosts，因此不会显示按钮。

当我们刷新页面时候触发了initShowPostNumber这个commit这时候shoPostNumber回到250，因此按钮就显示了。

2017-07-26 03:04 UTC, closed without merging