修复了一些在task详细页面的问题
zkuang/laixi-vue pull request #5
Opened 2017-07-11 17:22 UTC by JefferyLiang

当task没有被assignee的时候，会出现报错的问题。

更新了一些样式。

2017-07-13 03:38 UTC, zkuang requested changes

2017-07-13 03:38 UTC, zkuang commented on src/components/Task.vue
> +    isAssignee () {
改成Assigned比较容易理解

2017-07-13 06:12 UTC, JefferyLiang commented on src/components/Task.vue
> +    isAssignee () {
提交了一个新的commit把isAssignee修改成Assigned。

2017-07-14 07:04 UTC, JefferyLiang commented on src/components/Task.vue
> +      })
该方法需要连续点击两次checkbox框才会有效，找了一会都发现了不了问题在哪里。

2017-08-07 12:32 UTC, closed without merging